import _ from "lodash";

const dir = "../assets/building/";

// make a new images array and fill  the array with `dir + `/image${index + 1}.jpg`
// and reverse the array
export const imagesj = _.reverse(
  _.range(1, 120).map((index) => dir + `/image${index}.jpg`),
);

export const images = _.reverse([
  // export const images = [
  require(dir + `/image1.jpg`),
  require(dir + `/image2.jpg`),
  require(dir + `/image3.jpg`),
  require(dir + `/image4.jpg`),
  require(dir + `/image5.jpg`),
  require(dir + `/image6.jpg`),
  require(dir + `/image7.jpg`),
  require(dir + `/image8.jpg`),
  require(dir + `/image9.jpg`),
  require(dir + `/image10.jpg`),
  require(dir + `/image11.jpg`),
  require(dir + `/image12.jpg`),
  require(dir + `/image13.jpg`),
  require(dir + `/image14.jpg`),
  require(dir + `/image15.jpg`),
  require(dir + `/image16.jpg`),
  require(dir + `/image17.jpg`),
  require(dir + `/image18.jpg`),
  require(dir + `/image19.jpg`),
  require(dir + `/image20.jpg`),
  require(dir + `/image21.jpg`),
  require(dir + `/image22.jpg`),
  require(dir + `/image23.jpg`),
  require(dir + `/image24.jpg`),
  require(dir + `/image25.jpg`),
  require(dir + `/image26.jpg`),
  require(dir + `/image27.jpg`),
  require(dir + `/image28.jpg`),
  require(dir + `/image29.jpg`),
  require(dir + `/image30.jpg`),
  require(dir + `/image31.jpg`),
  require(dir + `/image32.jpg`),
  require(dir + `/image33.jpg`),
  require(dir + `/image34.jpg`),
  require(dir + `/image35.jpg`),
  require(dir + `/image36.jpg`),
  require(dir + `/image37.jpg`),
  require(dir + `/image38.jpg`),
  require(dir + `/image39.jpg`),
  require(dir + `/image40.jpg`),
  require(dir + `/image41.jpg`),
  require(dir + `/image42.jpg`),
  require(dir + `/image43.jpg`),
  require(dir + `/image44.jpg`),
  require(dir + `/image45.jpg`),
  require(dir + `/image46.jpg`),
  require(dir + `/image47.jpg`),
  require(dir + `/image48.jpg`),
  require(dir + `/image49.jpg`),
  require(dir + `/image50.jpg`),
  require(dir + `/image51.jpg`),
  require(dir + `/image52.jpg`),
  require(dir + `/image53.jpg`),
  require(dir + `/image54.jpg`),
  require(dir + `/image55.jpg`),
  require(dir + `/image56.jpg`),
  require(dir + `/image57.jpg`),
  require(dir + `/image58.jpg`),
  require(dir + `/image59.jpg`),
  require(dir + `/image60.jpg`),
  require(dir + `/image61.jpg`),
  require(dir + `/image62.jpg`),
  require(dir + `/image63.jpg`),
  require(dir + `/image64.jpg`),
  require(dir + `/image65.jpg`),
  require(dir + `/image66.jpg`),
  require(dir + `/image67.jpg`),
  require(dir + `/image68.jpg`),
  require(dir + `/image69.jpg`),
  require(dir + `/image70.jpg`),
  require(dir + `/image71.jpg`),
  require(dir + `/image72.jpg`),
  require(dir + `/image73.jpg`),
  require(dir + `/image74.jpg`),
  require(dir + `/image75.jpg`),
  require(dir + `/image76.jpg`),
  require(dir + `/image77.jpg`),
  require(dir + `/image78.jpg`),
  require(dir + `/image79.jpg`),
  require(dir + `/image80.jpg`),
  require(dir + `/image81.jpg`),
  require(dir + `/image82.jpg`),
  require(dir + `/image83.jpg`),
  require(dir + `/image84.jpg`),
  require(dir + `/image85.jpg`),
  require(dir + `/image86.jpg`),
  require(dir + `/image87.jpg`),
  require(dir + `/image88.jpg`),
  require(dir + `/image89.jpg`),
  require(dir + `/image90.jpg`),
  require(dir + `/image91.jpg`),
  require(dir + `/image92.jpg`),
  require(dir + `/image93.jpg`),
  require(dir + `/image94.jpg`),
  require(dir + `/image95.jpg`),
  require(dir + `/image96.jpg`),
  require(dir + `/image97.jpg`),
  require(dir + `/image98.jpg`),
  require(dir + `/image99.jpg`),
  require(dir + `/image100.jpg`),
  require(dir + `/image101.jpg`),
  require(dir + `/image102.jpg`),
  require(dir + `/image103.jpg`),
  require(dir + `/image104.jpg`),
  require(dir + `/image105.jpg`),
  require(dir + `/image106.jpg`),
  require(dir + `/image107.jpg`),
  require(dir + `/image108.jpg`),
  require(dir + `/image109.jpg`),
  require(dir + `/image110.jpg`),
  require(dir + `/image111.jpg`),
  require(dir + `/image112.jpg`),
  require(dir + `/image113.jpg`),
  require(dir + `/image114.jpg`),
  require(dir + `/image115.jpg`),
  require(dir + `/image116.jpg`),
  require(dir + `/image117.jpg`),
  require(dir + `/image118.jpg`),
  require(dir + `/image119.jpg`),
]);
